In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(
"retail_sales.csv",
parse_dates=["Date"],
dtype={
"Category": "category",
"Region" : "category"

}
# convert Date column to datetime

)

df.head()

        Date     Category        Sales  Quantity      Profit Region
0 2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1 2023-01-01     Clothing   958.520710       7.0  224.054049   East
2 2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3 2023-01-01       Sports  1230.230419       6.0  123.310460   West
4 2023-01-01         NaN?   828.585950      12.0   88.591355   East

In [4]:
# Sort by Age ascending, then Salary descending
df_sorted = df.sort_values(by=['Quantity', 'Sales'], ascending=[False, True])
print("Sorted the DataFrame")
df_sorted.head()

Sorted the DataFrame

           Date    Category       Sales  Quantity      Profit Region
312  2023-03-04  Home Goods    0.000000      19.0    0.000000   West
528  2023-04-16      Sports    0.000000      19.0  270.577388   West
1708 2023-12-08      Sports  227.942727      19.0   61.534381  North
571  2023-04-25    Clothing  361.006937      19.0   57.285585   West
1213 2023-08-31      Sports  368.305917      19.0   73.419555   West

In [5]:
# Rank Salary within Age groups
df['Sales_rank'] = df.groupby('Quantity')['Sales'].rank(method='dense', ascending=False)
print("\nSales Rank within Quantity gfoups:\n", df)

Sales Rank within Quantity gfoups:
            Date     Category        Sales  Quantity      Profit Region  \
0    2023-01-01  Electronics  1149.014246      11.0  383.664245  North
1    2023-01-01     Clothing   958.520710       7.0  224.054049   East
2    2023-01-01   Home Goods  1473.763845       2.0  466.593090  South
3    2023-01-01       Sports  1230.230419       6.0  123.310460   West
4    2023-01-01         NaN?   828.585950      12.0   88.591355   East
...         ...          ...          ...       ...         ...    ...
1820 2023-12-31  Electronics  1132.749004      14.0  353.464221   West
1821 2023-12-31     Clothing   679.261971       8.0  183.860200  North
1822 2023-12-31   Home Goods  1193.733728      10.0  359.010938  South
1823 2023-12-31       Sports  1076.118706      17.0  259.570916  North
1824 2023-12-31        Books   703.973443      14.0  134.106006   East

      Sales_rank
0           29.0
1           56.0
2            7.0
3           24.0
4           68.0
...          ...
1820        30.0
1821        88.0
1822        32.0
1823        38.0
1824        73.0

[1825 rows x 7 columns]